### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by moha-b** [mselim7/Claculator-HTML-CSS-JS#1]
## Alignment Issue
Specifically, when the result of a calculation is too `large` to fit within the display area of the calculator, the result is **not aligned** properly and extends beyond the edge of the screen.
u can see it right here
![image](https://user-images.githubusercontent.com/73842931/228862244-5bf8c188-9bc2-4784-aa22-eb6072af04ec.png)

**Comment by mselim7** [comment]
u mean the design not the operations right ?

**Comment by mselim7** [comment]
I'll fix it soon

**Comment by mselim7** [comment]
check it now I fixed it

**Comment by moha-b** [comment]
ياخى اتقى الله ياخى XD


![image](https://user-images.githubusercontent.com/73842931/228870725-5d64e639-1ff5-4654-911f-95e0f60e7c26.png)

**Comment by mselim7** [comment]
done
