### ISSUE TITLE
Three operands bug

### ISSUE THREAD

**Issue by Bad-ri** [mselim7/Claculator-HTML-CSS-JS#2]
You didn't show If the calculator is designed to handle only two operands or three?
so, it could be considered a bug if it allows three operands for any operator. Here is a test case to check for this bug:
Test case for three operands:
Input: 5 + 3 * 2
Expected output: Error message "Invalid expression."
so, the calculator should be updated to handle only two operands for each operator, or it should be updated to support operators that can handle multiple operands.
in the link below i send to you some test cases that fails when i try to test your calculator.
[Excel file](https://github.com/Bad-ri/Manual-Testing/tree/main/Calculator)

**Comment by mselim7** [comment]
I really appreciate the effort you have contributed to my simple project and I will work on this bug soon
