### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by Bad-ri** [mselim7/Claculator-HTML-CSS-JS#3]
The border inside the button is too thick, you should reduce it a little bit.
Also the calculator body appear in the bottom of the screen in my device and i think it should be higher.
![Screenshot (2)](https://user-images.githubusercontent.com/74131474/229088005-73d15887-eb70-4e1b-b64f-b0067f936428.png)

**Comment by mselim7** [comment]
about the stroke width has been reduced from 2.5 to 1.75 to be more simple, about the responsivity if the calculator body i will handle it soon

**Comment by Bad-ri** [comment]
done
